[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-tam", "tesseract-ocr-eng"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
